### ISSUE TITLE
Would it be possible to merge two records by overwriting any duplicate fields?

### ISSUE THREAD

**Issue by Wizek** [PkmX/rawr#7]
Allowing, for example:

```hs
>>> R ( #foo := 1, #bar := 2) :**: R ( #foo := 3)
R ( bar := 2, foo := 3 )
```

I've also had the same question for the Bookkeeper library: https://github.com/turingjump/bookkeeper/issues/6#issuecomment-288327786.

I hope I can find an answer for one of the record libraries so I can choose that for my projects.

**Comment by PkmX** [comment]
Yes. In the git version there is the updating operator `:<=` that overwrites fields in lhs with rhs.

```haskell
>>> R ( #a := (1 :: Int) ) :<= R ( #a := True )
R ( a := True )
```

I should upload the new version to Hackage so it also picks up some latest changes.

**Comment by Wizek** [comment]
Sounds great! I shall give this a try then!
